-- ====================================
-- 食谱推荐系统 - 数据库表创建和数据初始化
-- ====================================
USE nutri_plan_db;
-- 1. 创建食谱表
CREATE TABLE IF NOT EXISTS `recipes` (
    `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` datetime(3) DEFAULT NULL,
    `updated_at` datetime(3) DEFAULT NULL,
    `deleted_at` datetime(3) DEFAULT NULL,
    `name` varchar(200) NOT NULL COMMENT '食谱名称',
    `description` text COMMENT '食谱描述',
    `image_url` varchar(500) DEFAULT NULL COMMENT '食谱图片URL',
    `meal_type` varchar(20) NOT NULL COMMENT '餐次类型: 早餐/午餐/晚餐/加餐',
    `energy` decimal(10, 2) NOT NULL COMMENT '能量 (kcal)',
    `protein` decimal(10, 2) NOT NULL COMMENT '蛋白质 (g)',
    `carbohydrate` decimal(10, 2) NOT NULL COMMENT '碳水化合物 (g)',
    `fat` decimal(10, 2) NOT NULL COMMENT '脂肪 (g)',
    `dietary_fiber` decimal(10, 2) DEFAULT NULL COMMENT '膳食纤维 (g)',
    `ingredients` text NOT NULL COMMENT '食材列表 (JSON格式)',
    `cooking_steps` text COMMENT '烹饪步骤',
    `cooking_time` int DEFAULT 0 COMMENT '烹饪时间（分钟）',
    `difficulty` varchar(20) DEFAULT NULL COMMENT '难度等级: 简单/中等/困难',
    PRIMARY KEY (`id`),
    KEY `idx_recipes_deleted_at` (`deleted_at`),
    KEY `idx_recipes_name` (`name`),
    KEY `idx_recipes_meal_type` (`meal_type`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '食谱表';

-- 2. 创建每日食谱计划表
CREATE TABLE IF NOT EXISTS `daily_recipe_plans` (
    `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` datetime(3) DEFAULT NULL,
    `updated_at` datetime(3) DEFAULT NULL,
    `deleted_at` datetime(3) DEFAULT NULL,
    `user_id` bigint UNSIGNED NOT NULL COMMENT '用户ID',
    `plan_name` varchar(200) DEFAULT NULL COMMENT '计划名称',
    `breakfast_recipe_id` bigint UNSIGNED NOT NULL COMMENT '早餐食谱ID',
    `lunch_recipe_id` bigint UNSIGNED NOT NULL COMMENT '午餐食谱ID',
    `dinner_recipe_id` bigint UNSIGNED NOT NULL COMMENT '晚餐食谱ID',
    `snack_recipe_id` bigint UNSIGNED DEFAULT NULL COMMENT '加餐食谱ID（可选）',
    `total_energy` decimal(10, 2) DEFAULT NULL COMMENT '总能量',
    `total_protein` decimal(10, 2) DEFAULT NULL COMMENT '总蛋白质',
    `total_carbohydrate` decimal(10, 2) DEFAULT NULL COMMENT '总碳水化合物',
    `total_fat` decimal(10, 2) DEFAULT NULL COMMENT '总脂肪',
    `target_energy` decimal(10, 2) DEFAULT NULL COMMENT '目标能量',
    `target_protein` decimal(10, 2) DEFAULT NULL COMMENT '目标蛋白质',
    `target_carbohydrate` decimal(10, 2) DEFAULT NULL COMMENT '目标碳水化合物',
    `target_fat` decimal(10, 2) DEFAULT NULL COMMENT '目标脂肪',
    `match_score` decimal(5, 2) DEFAULT NULL COMMENT '匹配度评分 (0-100)',
    `is_selected` tinyint(1) DEFAULT 0 COMMENT '是否被用户选择',
    PRIMARY KEY (`id`),
    KEY `idx_daily_recipe_plans_deleted_at` (`deleted_at`),
    KEY `idx_daily_recipe_plans_user_id` (`user_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '每日食谱计划表';

-- ====================================
-- 示例食谱数据
-- ====================================

-- 早餐食谱
INSERT INTO
    `recipes` (
        `name`,
        `description`,
        `image_url`,
        `meal_type`,
        `energy`,
        `protein`,
        `carbohydrate`,
        `fat`,
        `dietary_fiber`,
        `ingredients`,
        `cooking_steps`,
        `cooking_time`,
        `difficulty`,
        `created_at`,
        `updated_at`
    )
VALUES (
        '燕麦牛奶粥',
        '营养丰富的早餐粥',
        '',
        '早餐',
        350,
        12,
        55,
        8,
        6,
        '["燕麦","牛奶","香蕉","坚果"]',
        '1. 燕麦加水煮熟\n2. 加入牛奶搅拌\n3. 切香蕉片\n4. 撒上坚果',
        15,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '全麦三明治',
        '健康全麦早餐',
        '',
        '早餐',
        380,
        18,
        45,
        12,
        5,
        '["全麦面包","鸡蛋","生菜","番茄","奶酪"]',
        '1. 煎鸡蛋\n2. 烤面包\n3. 夹入蔬菜和奶酪',
        10,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '水果酸奶碗',
        '清爽健康早餐',
        '',
        '早餐',
        320,
        15,
        50,
        6,
        4,
        '["希腊酸奶","草莓","蓝莓","蜂蜜","格兰诺拉麦片"]',
        '1. 酸奶倒入碗中\n2. 摆放水果\n3. 撒上麦片',
        5,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '鸡蛋蔬菜卷饼',
        '高蛋白早餐',
        '',
        '早餐',
        400,
        22,
        40,
        15,
        3,
        '["全麦tortilla","鸡蛋","菠菜","蘑菇","奶酪"]',
        '1. 炒蔬菜\n2. 炒鸡蛋\n3. 包进卷饼',
        12,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '豆浆油条套餐',
        '传统中式早餐',
        '',
        '早餐',
        420,
        14,
        60,
        12,
        2,
        '["豆浆","油条","茶叶蛋"]',
        '购买成品或自制',
        5,
        '简单',
        NOW(),
        NOW()
    );

-- 午餐食谱
INSERT INTO
    `recipes` (
        `name`,
        `description`,
        `image_url`,
        `meal_type`,
        `energy`,
        `protein`,
        `carbohydrate`,
        `fat`,
        `dietary_fiber`,
        `ingredients`,
        `cooking_steps`,
        `cooking_time`,
        `difficulty`,
        `created_at`,
        `updated_at`
    )
VALUES (
        '烤鸡胸配糙米',
        '高蛋白低脂午餐',
        '',
        '午餐',
        550,
        45,
        60,
        12,
        8,
        '["鸡胸肉","糙米","西兰花","胡萝卜"]',
        '1. 鸡胸肉腌制烤制\n2. 糙米煮熟\n3. 蔬菜蒸熟',
        35,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '三文鱼藜麦饭',
        'Omega-3丰富',
        '',
        '午餐',
        600,
        35,
        55,
        22,
        7,
        '["三文鱼","藜麦","芦笋","柠檬"]',
        '1. 三文鱼煎熟\n2. 藜麦煮熟\n3. 芦笋炒制',
        30,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '牛肉蔬菜炒面',
        '均衡营养午餐',
        '',
        '午餐',
        580,
        32,
        70,
        18,
        6,
        '["牛肉","全麦面条","彩椒","豆芽","酱油"]',
        '1. 牛肉切片炒熟\n2. 蔬菜快炒\n3. 面条煮熟翻炒',
        25,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '鸡肉沙拉碗',
        '低卡高蛋白',
        '',
        '午餐',
        480,
        40,
        45,
        14,
        9,
        '["鸡胸肉","生菜","番茄","黄瓜","牛油果","柠檬汁"]',
        '1. 鸡肉烤熟切片\n2. 蔬菜切块\n3. 加调味料拌匀',
        20,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '豆腐蔬菜煲',
        '素食健康午餐',
        '',
        '午餐',
        450,
        25,
        55,
        15,
        10,
        '["豆腐","香菇","青菜","姜蒜","糙米"]',
        '1. 豆腐煎至金黄\n2. 蔬菜炒香\n3. 加水煮成煲',
        30,
        '中等',
        NOW(),
        NOW()
    );

-- 晚餐食谱
INSERT INTO
    `recipes` (
        `name`,
        `description`,
        `image_url`,
        `meal_type`,
        `energy`,
        `protein`,
        `carbohydrate`,
        `fat`,
        `dietary_fiber`,
        `ingredients`,
        `cooking_steps`,
        `cooking_time`,
        `difficulty`,
        `created_at`,
        `updated_at`
    )
VALUES (
        '清蒸鱼配蔬菜',
        '低脂健康晚餐',
        '',
        '晚餐',
        420,
        35,
        30,
        15,
        5,
        '["鲈鱼","姜","葱","油菜","蒸鱼豉油"]',
        '1. 鱼清洗腌制\n2. 蒸15分钟\n3. 蔬菜清炒',
        25,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '鸡肉蘑菇炖饭',
        '温暖舒适晚餐',
        '',
        '晚餐',
        500,
        32,
        55,
        14,
        6,
        '["鸡肉","蘑菇","糙米","洋葱","高汤"]',
        '1. 鸡肉煎熟\n2. 蘑菇炒香\n3. 米饭慢炖',
        40,
        '中等',
        NOW(),
        NOW()
    ),
    (
        '虾仁炒时蔬',
        '海鲜健康晚餐',
        '',
        '晚餐',
        380,
        28,
        35,
        12,
        7,
        '["虾仁","西兰花","胡萝卜","荷兰豆","姜蒜"]',
        '1. 虾仁腌制\n2. 蔬菜焯水\n3. 快炒出锅',
        20,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '牛肉蔬菜汤',
        '营养丰富晚餐',
        '',
        '晚餐',
        450,
        30,
        40,
        16,
        8,
        '["牛肉","番茄","土豆","胡萝卜","洋葱"]',
        '1. 牛肉焯水\n2. 所有食材炖煮\n3. 调味即可',
        50,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '烤鸡腿配烤蔬菜',
        '简单美味晚餐',
        '',
        '晚餐',
        480,
        38,
        32,
        20,
        5,
        '["鸡腿","红薯","西葫芦","彩椒","橄榄油"]',
        '1. 鸡腿腌制\n2. 蔬菜切块\n3. 一起烤制',
        45,
        '简单',
        NOW(),
        NOW()
    );

-- 加餐食谱
INSERT INTO
    `recipes` (
        `name`,
        `description`,
        `image_url`,
        `meal_type`,
        `energy`,
        `protein`,
        `carbohydrate`,
        `fat`,
        `dietary_fiber`,
        `ingredients`,
        `cooking_steps`,
        `cooking_time`,
        `difficulty`,
        `created_at`,
        `updated_at`
    )
VALUES (
        '坚果拼盘',
        '健康零食',
        '',
        '加餐',
        180,
        6,
        12,
        14,
        3,
        '["杏仁","核桃","腰果","葡萄干"]',
        '直接食用',
        0,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '希腊酸奶',
        '高蛋白小食',
        '',
        '加餐',
        150,
        15,
        12,
        5,
        0,
        '["希腊酸奶","蜂蜜"]',
        '搅拌即食',
        2,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '水果拼盘',
        '维生素补充',
        '',
        '加餐',
        120,
        2,
        28,
        1,
        4,
        '["苹果","橙子","猕猴桃"]',
        '切块摆盘',
        5,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '全麦饼干配花生酱',
        '能量补充',
        '',
        '加餐',
        200,
        8,
        22,
        10,
        3,
        '["全麦饼干","天然花生酱"]',
        '涂抹即食',
        2,
        '简单',
        NOW(),
        NOW()
    ),
    (
        '香蕉蛋白奶昔',
        '运动后加餐',
        '',
        '加餐',
        220,
        20,
        25,
        6,
        2,
        '["香蕉","蛋白粉","牛奶"]',
        '搅拌机打匀',
        3,
        '简单',
        NOW(),
        NOW()
    );

-- ====================================
-- 数据导入完成
-- ====================================
-- 共导入 20 条食谱数据
-- - 早餐: 5 条
-- - 午餐: 5 条
-- - 晚餐: 5 条
-- - 加餐: 5 条